Repository NOAA-OWP/inundation-mapping, pull requests merged in 2020-12, with the labels that each got.

#135 Hotfix for unnessesary lake poly delete
  lib/snap_and_clip_to_nhd.py
Labels: bug

#142 [1pt] PR: Remove ocean FIM
  config/params_calibrated.env
  config/params_template.env
  lib/run_by_unit.sh
  lib/snap_and_clip_to_nhd.py
  lib/split_flows.py
  tests/aggregate_metrics.py
  tests/synthesize_test_cases.py
Labels: enhancement

#143 Updates to preprocessing scripts and remove incomplete output folders
  README.md
  lib/acquire_and_preprocess_inputs.py
  lib/aggregate_vector_inputs.py
  lib/run_by_unit.sh
Labels: enhancement

#169 PR: Error handling for empty stream network in coastal/lake hucs
  lib/run_by_unit.sh
  lib/split_flows.py
Labels: bug

#163 [1pt] PR: Fix for >0 no data values & masking Great Lakes water bodies
  lib/run_by_unit.sh
  lib/snap_and_clip_to_nhd.py
Labels: bug, enhancement
