Repository NOAA-OWP/inundation-mapping, pull requests merged in 2021-03, with the labels that each got.

#291 Update README.md
  README.md
Labels: bug, documentation

#296 [1pt] PR: Added features to aggregate_outputs.py
  CHANGELOG.md
  fim_run.sh
  src/aggregate_fim_outputs.py
Labels: enhancement

#298 [1pt] PR: Generate flow files for CatFIM
  .gitignore
  CHANGELOG.md
  Dockerfile.dev
  Pipfile
  Pipfile.lock
  src/add_crosswalk.py
  tools/.env.template
  tools/.gitignore
  tools/generate_categorical_fim.py
  tools/generate_categorical_fim_flows.py
  tools/tools_shared_functions.py
Labels: CatFIM

#320 [1pt] PR: Patch synthesize test cases
  CHANGELOG.md
  tools/synthesize_test_cases.py
Labels: bug

#319 [3pt] PR: Dev Catfim spatial
  CHANGELOG.md
  tools/generate_categorical_fim.py
  tools/generate_categorical_fim_flows.py
  tools/generate_categorical_fim_mapping.py
  tools/inundation.py
  tools/tools_shared_functions.py
Labels: CatFIM

#327 [1pt] Add detail/information to plotting capabilities (Dev-plot-update)
  CHANGELOG.md
  tools/eval_plots.py
  tools/plots/__init__.py
  tools/plots/plot_functions.py
Labels: enhancement
