Repository NOAA-OWP/inundation-mapping, pull requests merged in 2021-04, with the labels that each got.

#336 [1pt] Update spatial option when performing eval plots (Dev plots spatial)
  CHANGELOG.md
  tools/eval_plots.py
Labels: bug

#332 [1pt] PR: Tool to compare synthetic rating curve with benchmark rating curve (sierra test)
  CHANGELOG.md
  fim_run.sh
  src/add_crosswalk.py
  src/output_cleanup.py
  src/rem.py
  src/run_by_unit.sh
  src/usgs_gage_crosswalk.py
  tools/rating_curve_comparison.py
Labels: Agile Story, enhancement

#338 [1pt] PR: Get USGS rating curves (FB: dev-usgs-rating-curve)
  CHANGELOG.md
  src/usgs_gage_crosswalk.py
  tools/rating_curve_comparison.py
  tools/rating_curve_get_usgs_curves.py
  tools/tools_shared_functions.py
Labels: enhancement

#340 [2pt] PR for bathy SRC prototype
  CHANGELOG.md
  config/params_calibrated.env
  config/params_template.env
  src/add_crosswalk.py
  src/bathy_rc_adjust.py
  src/output_cleanup.py
  src/run_by_unit.sh
  tools/eval_plots.py
Labels: Rating Curves, enhancement

#355 [1pt] PR: Add mainstems attribute for sierra test. (FB: Dev-hotfix-usgs-gages)
  CHANGELOG.md
  src/run_by_unit.sh
  src/usgs_gage_crosswalk.py
  tools/.env.template
  tools/rating_curve_get_usgs_curves.py
Labels: bug

#359 [1pt] PR: Fix cleanup list. dev-cleanup-hotfix
  CHANGELOG.md
  src/output_cleanup.py
Labels: bug

#358 NHDPlus HR raster preprocessing
  CHANGELOG.md
  README.md
  src/acquire_and_preprocess_inputs.py
  src/bathy_rc_adjust.py
  src/burn_in_levees.py
  src/preprocess_rasters.py
  src/run_by_unit.sh
  src/usgs_gage_crosswalk.py
  src/utils/reproject_dem.py
  src/utils/shared_functions.py
  src/utils/shared_variables.py
  tools/comparing_src.py
  tools/generate_categorical_fim.py
  tools/generate_categorical_fim_mapping.py
Labels: bug

#356 closing multiprocessing pool objects
  CHANGELOG.md
  src/acquire_and_preprocess_inputs.py
  src/aggregate_fim_outputs.py
  tools/cache_metrics.py
  tools/generate_categorical_fim_mapping.py
  tools/rating_curve_comparison.py
  tools/synthesize_test_cases.py
Labels: bug

#363 [1pt] PR Update plotting script to not error out if FR or MS are not analyzed when using spatial argument
  CHANGELOG.md
  tools/eval_plots.py
  tools/generate_categorical_fim.py
Labels: bug

#365 [1pt] PR: Incorporate CatFIM flows into Sierra Test and add AHPS benchmark preprocessing scripts.
  CHANGELOG.md
  tools/.env.template
  tools/eval_plots.py
  tools/preprocess_ahps_nws.py
  tools/preprocess_ahps_usgs.py
  tools/preprocess_download_usgs_grids.py
  tools/rating_curve_comparison.py
  tools/rating_curve_get_usgs_curves.py
  tools/tools_shared_functions.py
Labels: enhancement

#367 Refactor synthesize_test_case.py to handle exceptions during multiprocessing
  CHANGELOG.md
  tools/inundation.py
  tools/run_test_case.py
Labels: bug
