Repository NOAA-OWP/inundation-mapping, pull requests merged in 2021-02, with the labels that each got.

#227 Post-process to aggregate FIM outputs to HUC6 scale
  CHANGELOG.md
  config/params_calibrated.env
  config/params_template.env
  fim_run.sh
  lib/acquire_and_preprocess_inputs.py
  lib/add_crosswalk.py
  lib/aggregate_fim_outputs.py
  lib/aggregate_vector_inputs.py
  lib/build_stream_traversal.py
  lib/clip_vectors_to_wbd.py
  lib/derive_headwaters.py
  lib/reachID_grid_to_vector_points.py
  lib/run_by_unit.sh
  lib/split_flows.py
Labels: enhancement

#253 Minor bug fixes
  CHANGELOG.md
  fim_run.sh
  lib/acquire_and_preprocess_inputs.py
Labels: bug

#256 Inundation wrappers for NWM recurrence flows or user-specified flow
  CHANGELOG.md
  tools/inundation_wrapper_custom_flow.py
  tools/inundation_wrapper_nwm_flows.py
Labels: enhancement

#261 [3pt] PR: Update MS Crosswalk Method to Address Gaps in FIM
  CHANGELOG.md
  fim_run.sh
  lib/add_crosswalk.py
  lib/build_stream_traversal.py
  lib/run_by_unit.sh
Labels: bug

#255 [1pt] PR: hotfix to aggregate script
  CHANGELOG.md
  lib/aggregate_fim_outputs.py
  lib/output_cleanup.py
Labels: bug

#254 [3pt] PR: Modifications to rem.py for exporting minimum thalweg elev for each hydroid
  CHANGELOG.md
  lib/rem.py
  lib/run_by_unit.sh
Labels: enhancement

#266 PR: Update short stream rating curves
  CHANGELOG.md
  config/params_calibrated.env
  config/params_template.env
  lib/acquire_and_preprocess_inputs.py
  lib/add_crosswalk.py
  lib/build_stream_traversal.py
  lib/filter_catchments_and_add_attributes.py
  lib/fr_to_ms_raster_mask.py
  lib/output_cleanup.py
  lib/run_by_unit.sh
  lib/split_flows.py
  lib/utils/shared_variables.py
  tests/inundation.py
Labels: bug, enhancement

#267 [3pt] PR: Enhancements to allow for evaluation at AHPS sites and generation of categorical FIM
  CHANGELOG.md
  tests/aggregate_metrics.py
  tests/all_ble_stats_comparison.py
  tests/ble_autoeval.sh
  tests/cache_metrics.py
  tests/run_test_case.py
  tests/synthesize_test_cases.py
  tests/utils/shared_functions.py
  tests/utils/shared_variables.py
  tools/generate_categorical_fim.py
  tools/inundation_wrapper_custom_flow.py
  tools/inundation_wrapper_nwm_flows.py
Labels: enhancement

#272 Adding HAND SRC datum elev values to hydroTable.csv output
  CHANGELOG.md
  lib/add_crosswalk.py
  lib/rem.py
Labels: enhancement

#275 [1pt] PR: Bug fixes to new evaluation code (dev-eval-bug-fixes)
  CHANGELOG.md
  README.md
  tests/inundation.py
  tests/run_test_case.py
  tests/synthesize_test_cases.py
  tests/utils/shared_variables.py
Labels: bug

#276 [3pt] PR: dev_eval_plots
  CHANGELOG.md
  tests/plots/eval_plots.py
  tests/plots/utils/__init__.py
  tests/plots/utils/shared_functions.py
Labels: enhancement
