Repository NOAA-OWP/inundation-mapping, pull requests merged in 2021-12, with the labels that each got.

#491 [1pt] PR: Added Probability Not Detected (PND) to evaluation code
  docs/CHANGELOG.md
  tools/eval_plots.py
  tools/synthesize_test_cases.py
  tools/tools_shared_functions.py
  tools/tools_shared_variables.py
Labels: enhancement, testing

#493 [1pt] PR: Adds ability to create a GPKG with joined rating curve comparison statistics
  docs/CHANGELOG.md
  tools/rating_curve_comparison.py
  tools/rating_curve_get_usgs_curves.py
  tools/tools_shared_functions.py
Labels: enhancement

#494 [2pt] PR: SRC adjustment enhancements and downstream application
  docs/CHANGELOG.md
  tools/adjust_rc_with_feedback.py
  tools/tools_shared_variables.py
Labels: enhancement, Rating Curves
