Repository NOAA-OWP/inundation-mapping, pull requests merged in 2021-11, with the labels that each got.

#475 [2pt] PR: Combine SRC modification modules in fim_run.sh post-processing step
  config/params_calibrated.env
  config/params_template.env
  docs/CHANGELOG.md
  fim_run.sh
  src/add_crosswalk.py
  src/bathy_rc_adjust.py
  src/bathy_src_adjust_topwidth.py
  src/identify_src_bankfull.py
  src/run_by_unit.sh
  src/vary_mannings_n_composite.py
  tools/run_test_case.py
Labels: enhancement, Rating Curves

#479 [1pt] PR: Patch updater.py after BARC merge
  api/node/updater/updater.py
  docs/CHANGELOG.md
Labels: Bug

#480 [1pt] PR: Hotfix for null discharge values from composite roughness calcs
  docs/CHANGELOG.md
  src/vary_mannings_n_composite.py
Labels: Bug

#481 [3pt] PR: Additional hydraulic properties to hydroTable
  docs/CHANGELOG.md
  src/add_crosswalk.py
  src/bathy_src_adjust_topwidth.py
  src/output_cleanup.py
  src/run_by_unit.sh
  src/vary_mannings_n_composite.py
Labels: enhancement, Rating Curves

#484 [1pt] PR: Hotfix for inundation composite
  docs/CHANGELOG.md
  tools/composite_ms_fr_inundation.py
  tools/run_test_case.py
  tools/run_test_case_gms.py
Labels: enhancement

#486 [1pt] PR: Hotfix for .csv file delete in SRC post-processing
  docs/CHANGELOG.md
  fim_run.sh
  src/add_crosswalk.py
  src/run_by_unit.sh
  src/vary_mannings_n_composite.py
Labels: Bug, Rating Curves

#488 [1pt] Update pip package to fix projection issue
  Pipfile
  Pipfile.lock
  docs/CHANGELOG.md
Labels: Bug, dependencies
