Repository NOAA-OWP/inundation-mapping, pull requests merged in 2021-06, with the labels that each got.

#393 [1pt] PR: BARC updates to cap xsec area and allow user to choose input bankfull geometry
  CHANGELOG.md
  config/params_calibrated.env
  config/params_template.env
  src/bathy_rc_adjust.py
  src/run_by_unit.sh
  tools/rating_curve_comparison.py
Labels: enhancement, testing

#395 [8pt] PR: Correct headwater assignment nws_lid layer
  CHANGELOG.md
  tools/generate_nws_lid.py
Labels: bug

#404 [8pt] Fim Run Memory Profiling
  CHANGELOG.md
  Dockerfile.dev
  Pipfile
  Pipfile.lock
  src/add_crosswalk.py
  src/adjust_thalweg_lateral.py
  src/agreedem.py
  src/burn_in_levees.py
  src/clip_vectors_to_wbd.py
  src/output_cleanup.py
  src/rem.py
  src/run_by_unit.sh
  src/time_and_tee_run_by_unit.sh
  src/unique_pixel_and_allocation.py
Labels: dependencies, enhancement

#415 [1pt] PR: Feature to evaluate alternative CatFIM technique performance
  CHANGELOG.md
  tools/eval_alt_catfim.py
  tools/synthesize_test_cases.py
Labels: CatFIM

#417 Thalweg Profile Tool and lateral Thalweg Adjustment Threshold
  CHANGELOG.md
  config/params_calibrated.env
  config/params_template.env
  src/adjust_headwater_streams.py
  src/adjust_thalweg_lateral.py
  src/aggregate_vector_inputs.py
  src/clip_vectors_to_wbd.py
  src/output_cleanup.py
  src/raster.py
  src/reachID_grid_to_vector_points.py
  src/reduce_nhd_stream_density.py
  src/run_by_unit.sh
  src/split_flows.py
  tools/thalweg_drop_check.py
Labels: Bug, CatFIM, enhancement
