Repository NOAA-OWP/inundation-mapping, pull requests merged in 2022-03, with the labels that each got.

#547 [1pt] PR: Append SRC optimization to fim_run.sh
  config/params_template.env
  docs/CHANGELOG.md
  fim_run.sh
  src/output_cleanup.py
  src/src_adjust_spatial_obs.py
  src/src_adjust_usgs_rating.py
  src/src_roughness_optimization.py
  src/utils/shared_functions.py
  src/utils/shared_variables.py
  tools/tools_shared_variables.py
Labels: enhancement, Rating Curves

#548 [2pts] PR: New Feature to remove stream orders 1 and 2 if desired via command arg
  docs/CHANGELOG.md
  gms_run_unit.sh
  src/gms/derive_level_paths.py
  src/gms/run_by_unit.sh
  src/gms/stream_branches.py
  unit_tests/gms/derive_level_paths_params.json
  unit_tests/gms/derive_level_paths_unittests.py
Labels: enhancement, FIM4

#550 [1pt] PR: FIM 4 USGS gage crosswalk and Sierra Test
  config/deny_gms_branches_default.lst
  config/deny_gms_branches_min.lst
  config/deny_gms_unit_default.lst
  docs/CHANGELOG.md
  gms_run_branch.sh
  src/gms/run_by_branch.sh
  src/gms/run_by_unit.sh
  src/usgs_gage_aggregate.py
  src/usgs_gage_crosswalk.py
  src/usgs_gage_unit_setup.py
  tools/rating_curve_comparison.py
  unit_tests/rating_curve_comparison_params.json
  unit_tests/rating_curve_comparison_unittests.py
  unit_tests/usgs_gage_crosswalk_params.json
  unit_tests/usgs_gage_crosswalk_unittests.py
Labels: FIM4

#561 [1pt] PR: Bug fixes for the Alpha Test to run in FIM 4
  docs/CHANGELOG.md
  tools/eval_plots.py
  tools/run_test_case.py
  tools/synthesize_test_cases.py
Labels: bug, FIM4

#566 Update FIM API dependency
  api/frontend/gui/requirements.txt
  api/node/connector/requirements.txt
Labels: API, dependencies

#568 [2pt] PR: Adds NLCD collation to collate_catchment_attributes.py
  docs/CHANGELOG.md
  tools/collate_catchment_attributes.py
Labels: enhancement, FIM3

#565 [1pt] PR: inundation raster mosaic functionality
  docs/CHANGELOG.md
  tools/composite_ms_fr_inundation.py
  tools/inundate_nation.py
  tools/inundation_mosaic_vrt.py
Labels: enhancement, FIM3

#570 [1pt] PR: Hotfix to address catchment aggregation with "src_calibrated" field
  docs/CHANGELOG.md
  src/aggregate_fim_outputs.py
Labels: bug
