Repository NOAA-OWP/inundation-mapping, pull requests merged in 2022-12, with the labels that each got.

#736 [2pt] PR: channel/overbank subdivision framework
  config/params_template.env
  docs/CHANGELOG.md
  gms_run_branch.sh
  src/add_crosswalk.py
  src/identify_src_bankfull.py
  src/src_adjust_spatial_obs.py
  src/src_adjust_usgs_rating.py
  src/src_roughness_optimization.py
  src/subdiv_chan_obank_src.py
  src/utils/shared_variables.py
  src/vary_mannings_n_composite.py
  tools/aggregate_csv_files.py
  tools/eval_plots.py
  tools/synthesize_test_cases.py
  tools/vary_mannings_n_composite.py
Labels: enhancement, Rating Curves, FIM4

#751 [1pt] Cleanup a few deny list files
  config/deny_gms_branches_dev.lst
  config/deny_gms_branches_prod.lst
  config/deny_gms_unit_prod.lst
  docs/CHANGELOG.md
Labels: bug, FIM4

#754 [1pt] PR: Hotfix: Stop writing `gms_inputs_removed.csv` if empty
  docs/CHANGELOG.md
  src/gms/remove_error_branches.py
Labels: bug, FIM4

#743 [1pt] PR: Dev fim4 alpha by catchments
  docs/CHANGELOG.md
  tools/pixel_counter.py
  tools/pixel_counter_functions.py
  tools/pixel_counter_wrapper.py
  tools/test_case_by_hydro_id.py
Labels: enhancement, FIM4

#767 [1pt] PR: Bug fix: `inundation.py` ignoring nodata
  docs/CHANGELOG.md
  tools/inundation.py
Labels: bug, FIM4

#769 [1pt] PR: Mask levee-protected areas from DEM
  docs/CHANGELOG.md
  src/gms/delineate_hydros_and_produce_HAND.sh
  src/gms/mask_dem.py
Labels: enhancement, FIM4

#753 [1pt] PR: Clip WBD to 3DEP DEM domain
  data/usgs/acquire_and_preprocess_3dep_dems.py
  docs/CHANGELOG.md
  src/clip_vectors_to_wbd.py
  src/gms/run_by_unit.sh
Labels: bug, FIM4

#772 [1pt] Update and renamed whitelists for hydrovis S3 put
  config/aws_s3_put_fim3_hydrovis_whitelist.lst
  config/aws_s3_put_fim4_hydrovis_whitelist.lst
  data/aws/s3.py
  docs/CHANGELOG.md
Labels: enhancement, FIM4

#758 [1pt] PR: Enhancements to CatFIM, rating curve generation script, and other files
  docs/CHANGELOG.md
  src/usgs_gage_crosswalk.py
  src/usgs_gage_unit_setup.py
  tools/eval_plots.py
  tools/generate_categorical_fim.py
  tools/generate_categorical_fim_flows.py
  tools/generate_categorical_fim_mapping.py
  tools/gms_tools/inundate_gms.py
  tools/pixel_counter.py
  tools/rating_curve_get_usgs_curves.py
  tools/test_case_by_hydro_id.py
  tools/tools_shared_functions.py
  tools/tools_shared_variables.py
Labels: enhancement, refactoring, Rating Curves, CatFIM, API, FIM4

#768 [1pt] Make GMS HAND post-processing independent
  docs/CHANGELOG.md
  gms_pipeline.sh
  gms_run_branch.sh
  gms_run_post_processing.sh
  gms_run_unit.sh
  src/bash_functions.env
  src/filter_catchments_and_add_attributes.py
  src/gms/delineate_hydros_and_produce_HAND.sh
  src/gms/derive_level_paths.py
  src/gms/run_by_unit.sh
  src/split_flows.py
  src/usgs_gage_unit_setup.py
  unit_tests/gms/derive_level_paths_params.json
  unit_tests/gms/derive_level_paths_unittests.py
Labels: enhancement, FIM4

#771 [1pt] Add rsync to docker image
  Dockerfile
  docs/CHANGELOG.md
Labels: enhancement, FIM4

#778 [1pt] PR: Bug fix to Stage-Based CatFIM
  docs/CHANGELOG.md
  tools/generate_categorical_fim.py
Labels: bug, CatFIM

#779 [1pt] PR: Remove `other` folder from `test_cases`
  config/symbology/esri/agreement_raster.lyr
  config/symbology/qgis/agreement_raster.qml
  docs/CHANGELOG.md
  tools/aggregate_metrics.py
  tools/cache_metrics.py
  tools/eval_alt_catfim.py
  tools/run_test_case.py
Labels: testing, Low Priority, FIM4

#773 [1pt] PR: Cleanup REM masking
  config/deny_gms_branch_zero.lst
  config/deny_gms_branches_dev.lst
  config/deny_gms_branches_prod.lst
  docs/CHANGELOG.md
  src/gms/delineate_hydros_and_produce_HAND.sh
  src/gms/rasterize_by_order.py
  src/gms/rem.py
Labels: bug, FIM4
