Repository NOAA-OWP/inundation-mapping, pull requests merged in 2022-09, with the labels that each got.

#672 [1pt] PR: Update derive level paths to use stream order
  docs/CHANGELOG.md
  src/gms/derive_level_paths.py
  src/gms/stream_branches.py
  unit_tests/gms/derive_level_paths_unittests.py
Labels: FIM4

#664 [1pt] Add tool to push data to S3 (for Hydroviz)
  .gitignore
  Dockerfile
  Pipfile
  Pipfile.lock
  config/aws_s3_put_whitelist.lst
  data/README.md
  data/__init__.py
  data/aws/.gitignore
  data/aws/aws_base.py
  data/aws/aws_creds_template.env
  data/aws/s3.py
  docs/CHANGELOG.md
  gms_run_branch.sh
  gms_run_unit.sh
  src/utils/shared_functions.py
Labels: bug, enhancement, FIM4

#678 Bug fixes for pruning lake branches and stream order prioritizing
  docs/CHANGELOG.md
  src/gms/stream_branches.py
Labels: bug, FIM4

#688 Cleanup CHANGELOG.md
  docs/CHANGELOG.md
Labels: documentation, FIM4

#681 [1pt] PR: Download USGS 3DEP Dems
  Dockerfile
  Dockerfile.prod
  data/acquire_and_preprocess_inputs.py
  data/create_vrt_file.py
  data/nws/preprocess_ahps_nws.py
  data/preprocess_rasters.py
  data/usgs/acquire_and_preprocess_3dep_dems.py
  data/usgs/preprocess_ahps_usgs.py
  data/usgs/preprocess_download_usgs_grids.py
  docs/CHANGELOG.md
  src/utils/shared_functions.py
  src/utils/shared_variables.py
Labels: enhancement, FIM4

#679 [1pt] PR: Fix thalweg notch
  docs/CHANGELOG.md
  src/clip_vectors_to_wbd.py
  src/run_by_unit.sh
  tools/pixel_counter.py
  tools/pixel_counter_functions.py
  tools/pixel_counter_wrapper.py
  tools/run_test_case.py
  tools/test_case_by_hydroid.py
Labels: bug, FIM3

#691 [1pt] Cleanup Branch Zero output at the end of a processing run
  config/deny_gms_branch_unittests.lst
  config/deny_gms_branch_zero.lst
  config/deny_gms_branches_dev.lst
  config/deny_gms_branches_prod.lst
  config/deny_gms_unit_prod.lst
  config/params_template.env
  docs/CHANGELOG.md
  gms_pipeline.sh
  gms_run_branch.sh
  gms_run_unit.sh
  src/gms/outputs_cleanup.py
  src/gms/run_by_branch.sh
  src/gms/run_by_unit.sh
  unit_tests/README.md
  unit_tests/__template_unittests.py
  unit_tests/filter_catchments_and_add_attributes_unittests.py
  unit_tests/gms/outputs_cleanup_params.json
  unit_tests/gms/outputs_cleanup_unittests.py
Labels: bug, High Priority, FIM4
