Repository NOAA-OWP/inundation-mapping, pull requests merged in 2022-08, with the labels that each got.

#641 [1pt] Updates to simplify usage of fim4 via gms_pipeline.sh
  README.md
  config/params_template_calibrated.env
  docs/CHANGELOG.md
  gms_pipeline.sh
  gms_run_branch.sh
  gms_run_unit.sh
  src/bash_functions.env
  src/check_huc_inputs.py
  src/check_unit_errors.py
  src/filter_catchments_and_add_attributes.py
  src/gms/derive_level_paths.py
  src/gms/run_by_unit.sh
  src/split_flows.py
  src/utils/fim_enums.py
  src/utils/shared_variables.py
  tools/copy_test_case_folders.py
  unit_tests/README.md
  unit_tests/check_unit_errors_params.json
  unit_tests/check_unit_errors_unittests.py
Labels: enhancement, FIM4

#642 [1pt] PR: Bug fix for missing `testing_versions` folder
  docs/CHANGELOG.md
  tools/run_test_case.py
Labels: bug, FIM4

#640 [2pt] PR: updates to inundation nation
  docs/CHANGELOG.md
  tools/inundate_nation.py
  tools/inundate_nation_composite.py
  tools/inundation_mosaic_vrt.py
  tools/inundation_wrapper_nwm_flows.py
Labels: enhancement, FIM3

#646 [1pt] PR: CatFIM patches and improvements
  docs/CHANGELOG.md
  tools/generate_categorical_fim.py
  tools/generate_categorical_fim_flows.py
  tools/generate_categorical_fim_mapping.py
Labels: bug, CatFIM, FIM3

#614 [1pt] PR: Adding step to trim catchments from levelpath
  docs/CHANGELOG.md
  src/gms/delineate_hydros_and_produce_HAND.sh
  src/split_flows.py
Labels: bug, enhancement, FIM4

#655 [1pt] Prune branches that fail with Exit status: 61 in split_flows.py
  docs/CHANGELOG.md
  gms_run_branch.sh
  src/gms/remove_error_branches.py
  tools/gms_tools/inundate_gms.py
Labels: bug, FIM4

#639 [1pt] PR: Adds USFIMR Data to Benchmark Capability
  docs/CHANGELOG.md
  tools/fimr_to_benchmark.py
Labels: enhancement, testing, FIM4

#652 [1pt] Update docker python packages for calibration db
  Dockerfile
  Pipfile
  Pipfile.lock
  docs/CHANGELOG.md
Labels: enhancement, FIM4

#657 [2pt] PR: FIM4 synthetic rating curve calibration functionality
  config/deny_gms_branch_zero.lst
  config/deny_gms_branches_min.lst
  config/deny_gms_unit_default.lst
  config/params_template.env
  docs/CHANGELOG.md
  gms_run_branch.sh
  src/add_crosswalk.py
  src/gms/run_by_unit.sh
  src/make_stages_and_catchlist.py
  src/src_adjust_spatial_obs.py
  src/src_adjust_usgs_rating.py
  src/src_roughness_optimization.py
  src/usgs_gage_aggregate.py
  src/usgs_gage_unit_setup.py
  src/utils/shared_functions.py
  src/utils/shared_variables.py
Labels: enhancement, Rating Curves, FIM4

#658 [2pt] PR: Patches for FIM4 alpha test
  src/gms/remove_error_branches.py
  tools/eval_plots.py
  tools/run_test_case.py
  tools/synthesize_test_cases.py
Labels: bug, FIM4

#665 [1pt] PR: hotfix for addressing missing input variable in gms_run_branch.sh
  docs/CHANGELOG.md
  gms_run_branch.sh
  src/src_adjust_spatial_obs.py
  src/src_roughness_optimization.py
Labels: bug, FIM4

#671 Prune branches in waterbodies
  docs/CHANGELOG.md
  src/gms/derive_level_paths.py
  src/gms/run_by_unit.sh
  src/gms/stream_branches.py
Labels: bug, FIM4
