Repository NOAA-OWP/inundation-mapping, pull requests merged in 2022-01, with the labels that each got.

#503 [1pt] PR: refinements to usgs_gage_crosswalk.py
  docs/CHANGELOG.md
  src/run_by_unit.sh
  src/usgs_gage_crosswalk.py
Labels: Bug, enhancement

#506 Adding catchments and streams to aggregate outputs folder
  docs/CHANGELOG.md
  src/aggregate_fim_outputs.py
Labels: enhancement

#507 [3pt] Updated pillow dependency to 9.0.0
  Pipfile.lock
Labels: dependencies

#509 [2pt] PR: Adjusting SRCs using USGS rating curves
  docs/CHANGELOG.md
  tools/adjust_rc_with_feedback.py
  tools/rating_curve_comparison.py
  tools/tools_shared_functions.py
  tools/usgs_gage_src_adjust.py
  tools/wrapper_usgs_gage_crosswalk.py
Labels: enhancement, Rating Curves

#508 [1pt] PR: Add AHPS Sites into rating curve comparison tools
  docs/CHANGELOG.md
  src/run_by_unit.sh
  src/usgs_gage_crosswalk.py
  tools/compare_water_surface_elev.py
  tools/rating_curve_comparison.py
  tools/rating_curve_get_usgs_curves.py
Labels: enhancement, Rating Curves

#512 Adding usgs_elev_table.csv to the -viz cleanup whitelist
  docs/CHANGELOG.md
  src/output_cleanup.py
Labels: Rating Curves

#514 [1pt] PR: SRC optimization code refinements
  docs/CHANGELOG.md
  tools/adjust_rc_with_feedback.py
  tools/rating_curve_comparison.py
  tools/usgs_gage_src_adjust.py
Labels: enhancement, Rating Curves
