Repository NOAA-OWP/inundation-mapping, pull requests merged in 2022-02, with the labels that each got.

#515 [1pt] PR: Hotfix for usgs_gage_crosswalk.py error in Hawaiian HUCs
  docs/CHANGELOG.md
  src/usgs_gage_crosswalk.py
Labels: bug, FIM3

#525 [1pt] PR: Adds basic unit test capabilities
  docs/CHANGELOG.md
  unit_tests/README.md
  unit_tests/clip_vectors_to_wbd_params.json
  unit_tests/clip_vectors_to_wbd_unittests.py
  unit_tests/gms/derive_level_paths_params.json
  unit_tests/gms/derive_level_paths_unittests.py
  unit_tests/unit_tests_utils.py
Labels: enhancement, testing

#526 [1pt] PR: Preliminary readme fixes and deletion of old Changelog
  CHANGELOG.md
  README.md
Labels: documentation

#529 [1pt] PR: Hotfix to address file cleanup in vary_mannings_n_composite.py
  docs/CHANGELOG.md
  fim_run.sh
  src/output_cleanup.py
  src/vary_mannings_n_composite.py
  tools/wrapper_usgs_gage_crosswalk.py
Labels: bug

#534 [1pt] PR: Updated evaluation code to accept ras2fim test cases
  docs/CHANGELOG.md
  tools/eval_plots.py
  tools/synthesize_test_cases.py
  tools/tools_shared_functions.py
  tools/tools_shared_variables.py
Labels: enhancement, testing

#536 Updated the iPython dependency to version 8.0.1
  Pipfile.lock
Labels: dependencies

#537 [1pt] PR: Updates to add multiple json nodes, a critical fix to method loading …
  unit_tests/README.md
  unit_tests/clip_vectors_to_wbd_params.json
  unit_tests/clip_vectors_to_wbd_unittests.py
  unit_tests/gms/derive_level_paths_params.json
  unit_tests/gms/derive_level_paths_unittests.py
Labels: testing

#538 [1pt] Adding unit test templates to make it easier to create new unit tests
  unit_tests/__example_nws_data_README.md
  unit_tests/__example_nws_data_params.json
  unit_tests/__example_nws_data_unittests.py
  unit_tests/__template_params.json
  unit_tests/__template_unittests.py
Labels: enhancement, testing, FIM4

#541 [1pt] PR: dev-fim3 readme updates
  README.md
Labels: documentation

#542 [1pt] PR: Tool to collate catchment attributes
  docs/CHANGELOG.md
  tools/collate_catchment_attributes.py
Labels: enhancement, FIM3

#540 [1pt] PR: Fix to suppress unit tests warnings
  unit_tests/__example_nws_data_unittests.py
  unit_tests/__template_unittests.py
  unit_tests/clip_vectors_to_wbd_unittests.py
  unit_tests/gms/derive_level_paths_unittests.py
Labels: enhancement, FIM4
