Repository NOAA-OWP/inundation-mapping, pull requests merged in 2022-10, with the labels that each got.

#711 [1pt] PR: Inundate-nation bug fixes and some minor upgrades
  docs/CHANGELOG.md
  tools/inundate_nation.py
Labels: bug, enhancement, FIM4

#701 [1pt] PR: FIM4 calibration database engine
  README.md
  config/calb_db_keys_template.env
  docs/CHANGELOG.md
  gms_run_branch.sh
  src/src_adjust_spatial_obs.py
  tools/calibration-db/README.md
  tools/calibration-db/docker-compose.yml
  tools/calibration-db/docker-entrypoint-initdb.d/init-db.sh
Labels: enhancement, FIM4

#700 [1pt] PR: Calibration DB Docker Compose Update
  docs/CHANGELOG.md
  tools/calibration/docker-compose.yml
Labels: bug, FIM3

#695 [1pt] PR: hotfix for FIM4 sierra test plots with branch zero
  docs/CHANGELOG.md
  tools/rating_curve_comparison.py
Labels: bug, testing, FIM4

#707 [1pt] Adds capability to produce single FIM3 rating curve comparison plots for each gage
  docs/CHANGELOG.md
  tools/rating_curve_comparison.py
Labels: enhancement, FIM3

#723 [1pt] PR: Runs branch 0 on HUCs without other branches after stream order filtering
  docs/CHANGELOG.md
  src/gms/buffer_stream_branches.py
  src/gms/derive_level_paths.py
  src/gms/generate_branch_list.py
  src/gms/stream_branches.py
Labels: bug, FIM4

#718 [1pt] PR: Port thalweg notch fix from FIM3
  docs/CHANGELOG.md
  src/clip_vectors_to_wbd.py
  src/gms/run_by_unit.sh
Labels: bug, FIM4

#727 [1pt] PR: Create HydroID - feature_id crosswalk table
  docs/CHANGELOG.md
  gms_run_branch.sh
  tools/gms_tools/combine_crosswalk_tables.py
Labels: enhancement, FIM4

#720 [1pt] PR: Add cblend (buffer) to acquire 3dep downloads
  data/create_vrt_file.py
  data/usgs/acquire_and_preprocess_3dep_dems.py
  docs/CHANGELOG.md
  src/gms/run_by_unit.sh
Labels: bug, FIM4

#690 [8pt] PR: Mask levee-protected areas from Relative Elevation Model
  config/deny_gms_branch_zero.lst
  config/deny_gms_branches_dev.lst
  config/deny_gms_branches_prod.lst
  config/deny_gms_unit_prod.lst
  config/params_template.env
  docs/CHANGELOG.md
  gms_run_branch.sh
  gms_run_unit.sh
  src/clip_vectors_to_wbd.py
  src/gms/delineate_hydros_and_produce_HAND.sh
  src/gms/rasterize_by_order.py
  src/gms/remove_error_branches.py
  src/gms/run_by_branch.sh
  src/gms/run_by_unit.sh
  src/gms/stream_branches.py
  src/split_flows.py
  tools/eval_alt_catfim.py
  tools/run_test_case.py
  unit_tests/README.md
  unit_tests/clip_vectors_to_wbd_params.json
  unit_tests/clip_vectors_to_wbd_unittests.py
Labels: enhancement, FIM4
