Repository NOAA-OWP/inundation-mapping, pull requests merged in 2023-09, with the labels that each got.

#983 [2pt] PR Hotfix for stacked bar Eval Plots
  docs/CHANGELOG.md
  tools/eval_plots_stackedbar.py
Labels: bug

#977 [1pt] PR: Bugfix: Correct `nodata` value in `src/mask_dem.py`
  docs/CHANGELOG.md
  src/buffer_stream_branches.py
  src/burn_in_levees.py
  src/generate_branch_list.py
  src/mask_dem.py
Labels: bug, refactoring, High Priority, FIM4

#970 [1pt] PR: Fix stream outlet clipping
  docs/CHANGELOG.md
  src/clip_vectors_to_wbd.py
  src/derive_level_paths.py
  src/run_unit_wb.sh
  src/stream_branches.py
  unit_tests/derive_level_paths_params.json
  unit_tests/derive_level_paths_test.py
Labels: bug, FIM4

#965 [1pt] PR: SRC calibration with ras2fim xsection rating data
  config/deny_branches.lst
  config/deny_unit.lst
  config/params_template.env
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/add_crosswalk.py
  src/aggregate_by_huc.py
  src/run_by_branch.sh
  src/run_unit_wb.sh
  src/src_adjust_ras2fim_rating.py
  src/src_roughness_optimization.py
  src/subdiv_chan_obank_src.py
  src/usgs_gage_crosswalk.py
  src/usgs_gage_unit_setup.py
  tools/inundate_nation.py
Labels: enhancement, Rating Curves

#987 [1pt]: PR: Bug fix for `src/usgs_gage_unit_setup.py`
  CITATION.cff
  docs/CHANGELOG.md
  src/usgs_gage_unit_setup.py
Labels: bug, FIM4

#992 [1pt] PR: Bugfix for `MultiLineString` unit error in `src/stream_branches.py`
  CITATION.cff
  docs/CHANGELOG.md
  pyproject.toml
  src/split_flows.py
  src/stream_branches.py
Labels: bug, FIM4

#993 [1pt] PR: Fix pandas and geopandas warnings
  data/usgs/preprocess_ahps_usgs.py
  data/write_parquet_from_calib_pts.py
  docs/CHANGELOG.md
  src/add_crosswalk.py
  src/bathy_src_adjust_topwidth.py
  src/crosswalk_nwm_demDerived.py
  src/derive_level_paths.py
  src/finalize_srcs.py
  src/identify_src_bankfull.py
  src/split_flows.py
  src/src_adjust_usgs_rating.py
  src/src_roughness_optimization.py
  src/stream_branches.py
  src/subdiv_chan_obank_src.py
  src/subset_catch_list_by_branch_id.py
  src/usgs_gage_unit_setup.py
  src/utils/shared_functions.py
  tools/adjust_rc_with_feedback.py
  tools/aggregate_csv_files.py
  tools/combine_crosswalk_tables.py
  tools/inundation.py
  tools/make_boxes_from_bounds.py
  tools/mosaic_inundation.py
  tools/plots.py
  tools/rating_curve_comparison.py
  tools/vary_mannings_n_composite.py
Labels: refactoring, FIM4

#990 [1pt] PR: Bug fix: set geometry after `GeoDataFrame.update()`
  CITATION.cff
  docs/CHANGELOG.md
  src/usgs_gage_unit_setup.py
Labels: bug, FIM4

#996 [1pt] PR: Update README.md for ESIP download details
  README.md
Labels: enhancement, High Priority, FIM4

#997 [1pt] PR: Bug fix for reindexing error
  docs/CHANGELOG.md
  src/stream_branches.py
Labels: bug, FIM4

#998 [1 pt]PR: Remove black exclude list
  .pre-commit-config.yaml
  docs/CHANGELOG.md
  pyproject.toml
  src/add_crosswalk.py
  src/bathy_src_adjust_topwidth.py
  src/bathymetric_adjustment.py
  src/identify_src_bankfull.py
  src/src_roughness_optimization.py
  tools/vary_mannings_n_composite.py
Labels: FIM4
