Repository NOAA-OWP/inundation-mapping, pull requests merged in 2023-01, with the labels that each got.

#781 [1pt] PR: Update hydrovis S3 push whitelist
  config/aws_s3_put_fim4_hydrovis_whitelist.lst
  docs/CHANGELOG.md
Labels: enhancement, FIM4

#780 [1pt] PR: Clip WBD and branch buffer polygons to DEM domain
  docs/CHANGELOG.md
  src/clip_vectors_to_wbd.py
  src/gms/buffer_stream_branches.py
  src/gms/derive_level_paths.py
  src/gms/mask_dem.py
  src/gms/remove_error_branches.py
  src/gms/run_by_unit.sh
  src/gms/toDo.md
  src/split_flows.py
Labels: bug, High Priority, FIM4

#760 [8pt] PR: Stacked Bar Eval Plots
  docs/CHANGELOG.md
  tools/eval_plots_stackedbar.py
Labels: enhancement, FIM4

#790 [1pt] PR: Remove Great Lakes clipping
  docs/CHANGELOG.md
  src/clip_vectors_to_wbd.py
  src/gms/run_by_unit.sh
Labels: refactoring, Low Priority, FIM4

#782 [1pt] PR: Change the projection of HAND processing to EPSG:5070
  data/nld/preprocess_levee_protected_areas.py
  data/usgs/acquire_and_preprocess_3dep_dems.py
  docs/CHANGELOG.md
  gms_run_post_processing.sh
  src/clip_vectors_to_wbd.py
  src/gms/run_by_unit.sh
  src/gms/stream_branches.py
  src/src_adjust_spatial_obs.py
  src/utils/shared_variables.py
  tools/inundate_nation.py
Labels: enhancement, FIM4

#796 [1pt] PR: Bug fix: combine_crosswalk_tables.py fails if only one HUC is run
  docs/CHANGELOG.md
  tools/gms_tools/combine_crosswalk_tables.py
Labels: bug, FIM4

#797 [1pt] PR: Consolidate bash environment variables into a single file
  config/mannings_default.json
  config/mannings_default_calibrated.json
  config/params_template.env
  docs/CHANGELOG.md
  gms_run_branch.sh
  gms_run_post_processing.sh
  gms_run_unit.sh
  src/add_crosswalk.py
  src/aggregate_vector_inputs.py
  src/bash_variables.env
  src/gms/run_by_branch.sh
  src/gms/run_by_unit.sh
  src/utils/shared_variables.py
Labels: refactoring, FIM4

#794 [1pt] PR: Remove fim3 files and refs
  api/.gitignore
  api/README.md
  api/frontend/.env-template
  api/frontend/docker-compose-dev.yml
  api/frontend/docker-compose-prod.yml
  api/frontend/gui/Dockerfile
  api/frontend/gui/entrypoint.sh
  api/frontend/gui/gui.py
  api/frontend/gui/requirements.txt
  api/frontend/gui/templates/index.html
  api/frontend/gui/wsgi.py
  api/frontend/nginx-dev.conf
  api/frontend/nginx-prod.conf
  api/frontend/output_handler/Dockerfile
  api/frontend/output_handler/entrypoint.sh
  api/frontend/output_handler/output_handler.py
  api/frontend/output_handler/requirements.txt
  api/node/.env-template
  api/node/connector/Dockerfile
  api/node/connector/connector.py
  api/node/connector/entrypoint.sh
  api/node/connector/requirements.txt
  api/node/docker-compose-dev.yml
  api/node/docker-compose-prod.yml
  api/node/nginx.conf
  api/node/updater/Dockerfile
  api/node/updater/entrypoint.sh
  api/node/updater/requirements.txt
  api/node/updater/updater.py
  data/preprocess_rasters.py
  docs/CHANGELOG.md
  fim_run.sh
  src/adjust_headwater_streams.py
  src/aggregate_fim_outputs.sh
  src/fr_to_ms_raster_mask.py
  src/get_all_huc_in_inputs.py
  src/gms/delineate_hydros_and_produce_HAND.sh
  src/gms/make_rem.py
  src/gms/toDo.md
  src/reduce_nhd_stream_density.py
  src/rem.py
  src/run_by_unit.sh
  src/time_and_tee_run_by_unit.sh
  src/utils/archive_cleanup.py
  tools/compare_gms_srcs_to_fr.py
  tools/cygnss_preprocessing.py
  tools/nesdis_preprocessing.py
  tools/preprocess_fimx.py
Labels: FIM4

#802 [1pt] PR: branch trimming for lake segments
  docs/CHANGELOG.md
  src/gms/stream_branches.py
Labels: enhancement, FIM4

#801 [1pt] PR: Fix error msg of stats object not referenced
  docs/CHANGELOG.md
  tools/pixel_counter.py
  tools/test_case_by_hydro_id.py
Labels: bug, FIM4
