Repository NOAA-OWP/inundation-mapping, pull requests merged in 2023-04, with the labels that each got.

#867 [1pt] PR: HUC outputs not be cleaned and erroring out
  docs/CHANGELOG.md
  fim_process_unit_wb.sh
  src/run_unit_wb.sh
Labels: bug, High Priority, FIM4

#858 [1pt] PR: Clip WBD to DEM domain
  data/wbd/preprocess_wbd.py
  docs/CHANGELOG.md
  src/clip_vectors_to_wbd.py
Labels: enhancement, refactoring, High Priority, FIM4

#868 [1pt] PR: post processing aggregate branch hydrotables to huc
  docs/CHANGELOG.md
  fim_pipeline.sh
  fim_post_processing.sh
  src/add_crosswalk.py
  src/aggregate_by_huc.py
  src/subdiv_chan_obank_src.py
  src/usgs_gage_aggregate.py
  tools/inundate_gms.py
  tools/inundation.py
Labels: enhancement, Rating Curves

#874 [1pt] PR: Hotfix for branch exit code 61 failing with temp directories
  docs/CHANGELOG.md
  fim_pipeline.sh
  src/process_branch.sh
Labels: bug

#879 [1pt] PR: Replace os.environ with input arguments
  docs/CHANGELOG.md
  fim_pre_processing.sh
  src/add_crosswalk.py
  src/check_huc_inputs.py
  src/delineate_hydros_and_produce_HAND.sh
  src/split_flows.py
Labels: refactoring, FIM4

#882 [1pt] PR: Check for empty output_catchments
  docs/CHANGELOG.md
  src/filter_catchments_and_add_attributes.py
Labels: bug, FIM4

#881 [1pt] PR: Clip branch 0 DEM-derived flowlines to terminal NWM streamlines
  docs/CHANGELOG.md
  src/delineate_hydros_and_produce_HAND.sh
  src/split_flows.py
Labels: bug, From Vlab, FIM4

#889 [3pt] PR: Update base GDAL Docker image and other Python packages
  Dockerfile
  Pipfile
  Pipfile.lock
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/add_crosswalk.py
  src/aggregate_by_huc.py
  src/build_stream_traversal.py
  src/getRasterInfoNative.py
  src/src_adjust_usgs_rating.py
  src/stream_branches.py
  src/usgs_gage_unit_setup.py
  tools/eval_plots.py
  tools/inundation.py
Labels: refactoring, dependencies, FIM4
