Repository NOAA-OWP/inundation-mapping, pull requests merged in 2023-08, with the labels that each got.

#950 [1pt] PR: Fix for aggregated hydrotable inundation
  docs/CHANGELOG.md
  tools/inundate_gms.py
  unit_tests/tools/inundate_gms_params.json
  unit_tests/tools/inundate_gms_test.py
  unit_tests/tools/inundate_gms_unittests.py
Labels: bug, FIM4

#952 [1pt] PR: Manually calibrate synthetic rating curves
  config/params_template.env
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/src_manual_calibration.py
Labels: enhancement, FIM4

#953 [1pt] PR: Bathymetry adjustment routine
  config/params_template.env
  data/bathymetry/preprocess_bathymetry.py
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/add_crosswalk.py
  src/aggregate_by_huc.py
  src/bathymetric_adjustment.py
  src/identify_src_bankfull.py
  src/subdiv_chan_obank_src.py
Labels: enhancement

#946 [1pt] PR: Fix acquire for ras2fim use
  README.md
  data/usgs/acquire_and_preprocess_3dep_dems.py
  docs/CHANGELOG.md
  fim_pipeline.sh
  fim_pre_processing.sh
  fim_process_unit_wb.sh
Labels: enhancement, FIM4

#959 [1pt] PR: Bathymetry adjustment hotfix
  config/params_template.env
  data/bathymetry/preprocess_bathymetry.py
  docs/CHANGELOG.md
  fim_post_processing.sh
Labels: bug

#956 Integrate GVAL In Synthesize Cases
  Dockerfile
  Pipfile
  Pipfile.lock
  docs/CHANGELOG.md
  tools/run_test_case.py
  tools/synthesize_test_cases.py
  tools/tools_shared_functions.py
  unit_tests/tools/inundate_gms_test.py
Labels: enhancement

#960 [1pt] PR: Update BLE benchmark data
  data/ble/ble_benchmark/Dockerfile
  data/ble/ble_benchmark/Pipfile
  data/ble/ble_benchmark/Pipfile.lock
  data/ble/ble_benchmark/README.md
  data/ble/ble_benchmark/create_ble_benchmark.py
  data/ble/ble_benchmark/create_flow_forecast_file.py
  data/ble/ble_benchmark/preprocess_benchmark.py
  docs/CHANGELOG.md
  tools/create_flow_forecast_file.py
Labels: testing

#948 [1pt] PR: Adds inundation and mosaic wrapper with polygon merging functionality
  docs/CHANGELOG.md
  tools/inundate_gms.py
  tools/inundate_mosaic_wrapper.py
  tools/mosaic_inundation.py
Labels: enhancement, FIM4
