Repository NOAA-OWP/inundation-mapping, pull requests merged in 2024-02, with the labels that each got.

#1073 [1pt] PR: Update pipfile and lock for dependabot fixes
  Pipfile
  Pipfile.lock
  docs/CHANGELOG.md
Labels: enhancement, dependencies

#1066 [1pt] PR: Add index to aggregated crosswalk table
  docs/CHANGELOG.md
  tools/combine_crosswalk_tables.py
Labels: enhancement

#1054 [2pt] PR: Updates for acquire, logging and cpu test
  .gitattributes
  .pre-commit-config.yaml
  CONTRIBUTING.md
  data/usgs/acquire_and_preprocess_3dep_dems.py
  data/usgs/preprocess_ahps_usgs.py
  data/usgs/preprocess_download_usgs_grids.py
  docs/CHANGELOG.md
  fim_pipeline.sh
  fim_post_processing.sh
  fim_pre_processing.sh
  fim_process_unit_wb.sh
  src/bash_functions.env
  src/delineate_hydros_and_produce_HAND.sh
  src/derive_level_paths.py
  src/run_by_branch.sh
  src/run_unit_wb.sh
  src/split_flows.py
Labels: bug, enhancement, FIM4
