Repository NOAA-OWP/inundation-mapping, pull requests merged in 2024-10, with the labels that each got.

#1314 [1pt] PR: Fix bugs from hand_4_5_10_0
  docs/CHANGELOG.md
  src/derive_level_paths.py
  src/run_unit_wb.sh
  src/stream_branches.py
Labels: bug

#1244 [1 pt] PR: New Flood Impact Assessment Tool
  docs/CHANGELOG.md
  tools/analyze_flood_impact.py
Labels: enhancement

#1306 [1pt] PR: Extend outlet levelpath(s) outside HUC
  config/deny_branch_zero.lst
  config/deny_branches.lst
  config/deny_unit.lst
  docs/CHANGELOG.md
  src/derive_level_paths.py
  src/run_by_branch.sh
  src/run_unit_wb.sh
  src/stream_branches.py
Labels: bug, High Priority, FIM4

#1298 [13pt] PR: Modifying OSM bridge scripts
  data/bridges/pull_osm_bridges.py
  docs/CHANGELOG.md
  src/bash_variables.env
  src/heal_bridges_osm.py
Labels: enhancement

#1318 [1pt] PR: Fix merge conflict bugs
  docs/CHANGELOG.md
  src/aggregate_by_huc.py
  src/bash_variables.env
  src/stream_branches.py
Labels: bug, High Priority, FIM4

#1322 [2pt] PR: docker file for OWP, non root user
  Dockerfile.dev
  Dockerfile.prod
  README.md
  docs/CHANGELOG.md
  fim_pipeline.sh
  fim_post_processing.sh
  fim_pre_processing.sh
  fim_process_unit_wb.sh
Labels: enhancement, High Priority, FIM4

#1320 [1ptt] PR: Fix error and warning scan bug
  docs/CHANGELOG.md
  fim_post_processing.sh
Labels: bug, FIM4
