Repository NOAA-OWP/inundation-mapping, pull requests merged in 2024-07, with the labels that each got.

#1204 [1pt] PR: Bug fix for extending outlets
  data/wbd/clip_vectors_to_wbd.py
  data/wbd/generate_pre_clip_fim_huc8.py
  docs/CHANGELOG.md
  src/bash_variables.env
Labels: bug

#1205 [1pt] PR: Snap crosswalk to NWM streams
  docs/CHANGELOG.md
  src/add_crosswalk.py
Labels: bug, enhancement

#1184 [1pt] PR: Added Bridge Inundation tool
  docs/CHANGELOG.md
  tools/bridge_inundation.py
Labels: enhancement

#1220 [3pt] PR: Updating hydroTable and src _full_crosswalked
  config/deny_branch_zero.lst
  config/deny_branches.lst
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/update_htable_src.py
Labels: enhancement

#1219 [1pt] PR: Change error messages to warnings
  docs/CHANGELOG.md
  src/bathymetric_adjustment.py
  src/src_roughness_optimization.py
Labels: bug, FIM4, good first issue

#1216 [1pt] PR: Add `NO_VALID_CROSSWALKS` to `FIM_exit_codes`
  docs/CHANGELOG.md
  src/add_crosswalk.py
  src/process_branch.sh
  src/utils/fim_enums.py
Labels: bug, good first issue

#1224 [1pt] PR: Remove warning messages
  docs/CHANGELOG.md
  src/adjust_thalweg_lateral.py
  src/delineate_hydros_and_produce_HAND.sh
  src/getRasterInfoNative.py
Labels: Low Priority, good first issue

#1222 [1pt] PR: log duration times per module for post processing
  docs/CHANGELOG.md
  fim_pipeline.sh
  fim_post_processing.sh
  src/bash_functions.env
Labels: enhancement, FIM4

#1217 [3pt] PR: Docker, python packages and jdk updates
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Pipfile
  Pipfile.lock
  config/aws_s3_put_fim3_hydrovis_whitelist.lst
  docs/CHANGELOG.md
  fim_pre_processing.sh
  pyproject.toml
  src/bathymetric_adjustment.py
  tools/overlapping_inundation.py
  unit_tests/README.md
  unit_tests/__template.json
  unit_tests/__template.py
  unit_tests/aggregate_branch_lists_params.json
  unit_tests/aggregate_branch_lists_test.py
  unit_tests/check_unit_errors_params.json
  unit_tests/check_unit_errors_test.py
  unit_tests/clip_vectors_to_wbd_params.json
  unit_tests/clip_vectors_to_wbd_test.py
  unit_tests/derive_level_paths_params.json
  unit_tests/derive_level_paths_test.py
  unit_tests/filter_catchments_and_add_attributes_params.json
  unit_tests/filter_catchments_and_add_attributes_test.py
  unit_tests/generate_branch_list_csv_params.json
  unit_tests/generate_branch_list_csv_test.py
  unit_tests/generate_branch_list_params.json
  unit_tests/generate_branch_list_test.py
  unit_tests/inundate_gms_params.json
  unit_tests/inundate_gms_test.py
  unit_tests/inundation_params.json
  unit_tests/inundation_test.py
  unit_tests/outputs_cleanup_params.json
  unit_tests/outputs_cleanup_test.py
  unit_tests/pyproject.toml
  unit_tests/rating_curve_comparison_params.json
  unit_tests/rating_curve_comparison_test.py
  unit_tests/shared_functions_params.json
  unit_tests/shared_functions_test.py
  unit_tests/split_flows_params.json
  unit_tests/split_flows_test.py
  unit_tests/unit_tests_utils.py
  unit_tests/usgs_gage_crosswalk_params.json
  unit_tests/usgs_gage_crosswalk_test.py
Labels: High Priority, dependencies, FIM4

#1233 [1pt] PR: Remove on screen warning from numpy for alpha tests
  docs/CHANGELOG.md
  tools/overlapping_inundation.py
Labels: bug, High Priority, FIM4
