Repository NOAA-OWP/inundation-mapping, pull requests merged in 2024-09, with the labels that each got.

#1271 [1pt] FIM Performance for Alaska and logging
  docs/CHANGELOG.md
  tools/test_case_by_hydro_id.py
Labels: bug, enhancement

#1267 [1pt] PR: Use fiona for writing files
  data/esri.py
  data/nld/levee_download.py
  data/usgs/acquire_and_preprocess_3dep_dems.py
  data/usgs/rating_curve_get_usgs_curves.py
  data/wbd/preprocess_wbd.py
  docs/CHANGELOG.md
  src/derive_headwaters.py
  src/derive_level_paths.py
  src/edit_points.py
  src/filter_catchments_and_add_attributes.py
  src/reachID_grid_to_vector_points.py
  src/split_flows.py
  src/src_adjust_spatial_obs.py
  src/src_roughness_optimization.py
  src/stream_branches.py
  tools/eval_plots.py
  tools/evaluate_continuity.py
  tools/generate_nws_lid.py
  tools/make_boxes_from_bounds.py
  tools/mosaic_inundation.py
  tools/rating_curve_comparison.py
  tools/test_case_by_hydro_id.py
Labels: bug

#1246 [1pt] PR: Mosaic depths and extents
  docs/CHANGELOG.md
  tools/inundate_mosaic_wrapper.py
Labels: bug

#1149 [1pt] PR: Catchment Boundary Tool Addition
  docs/CHANGELOG.md
  tools/identify_catchment_boundary.py
Labels: enhancement, Hold

#1165 [1pt] Fix CatFIM to re-run stage based (Catfim V2.0)
  .pre-commit-config.yaml
  config/catfim_template.env
  docs/CHANGELOG.md
  pyproject.toml
  src/utils/fim_logger.py
  src/utils/shared_variables.py
  tools/generate_categorical_fim.py
  tools/generate_categorical_fim_flows.py
  tools/generate_categorical_fim_mapping.py
  tools/generate_nws_lid.py
  tools/mosaic_inundation.py
  tools/tools_shared_functions.py
Labels: CatFIM

#1291 [1pt] PR: Change Docker base image and stop Whitebox downloads
  Dockerfile
  Pipfile
  Pipfile.lock
  docs/CHANGELOG.md
  fim_pre_processing.sh
  src/agreedem.py
  src/unique_pixel_and_allocation.py
  tools/aggregate_mannings_calibration.py
  tools/eval_plots.py
  tools/generate_nws_lid.py
  tools/synthesize_test_cases.py
Labels: High Priority, dependencies

#1301 [1pt]: PR: Reload 3dep DEMs and pre-clips
  CITATION.cff
  data/usgs/acquire_and_preprocess_3dep_dems.py
  data/wbd/generate_pre_clip_fim_huc8.py
  data/wbd/preprocess_wbd.py
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/bash_variables.env
  tools/rating_curve_comparison.py
Labels: bug, enhancement, Hold
