Repository NOAA-OWP/inundation-mapping, pull requests merged in 2024-05, with the labels that each got.

#1133 [1pt] PR: Bug fix to prevent `listdir()` from returning filenames
  docs/CHANGELOG.md
  src/bathy_src_adjust_topwidth.py
  src/identify_src_bankfull.py
  src/subdiv_chan_obank_src.py
  src/utils/shared_functions.py
  tools/vary_mannings_n_composite.py
Labels: bug

#1121 [1pt] PR: Clip ocean mask from DEM and extend outlet streams
  data/wbd/clip_vectors_to_wbd.py
  data/wbd/generate_pre_clip_fim_huc8.py
  docs/CHANGELOG.md
Labels: bug

#1122 [21pt] PR: Adding Open Street Map bridge data pulling and healing scripts
  Pipfile
  Pipfile.lock
  data/bridges/pull_osm_bridges.py
  data/wbd/clip_vectors_to_wbd.py
  data/wbd/generate_pre_clip_fim_huc8.py
  docs/CHANGELOG.md
  src/bash_variables.env
  src/delineate_hydros_and_produce_HAND.sh
  src/heal_bridges_osm.py
  src/utils/shared_functions.py
  src/utils/shared_variables.py
Labels: enhancement

#1144 1pt [PR] Add pre-commit and deploy notes
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation, FIM4

#1150 [1pt] PR: v4.5.0.0 bug fixes
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CHANGELOG.md
  src/add_crosswalk.py
  src/bash_variables.env
  src/delineate_hydros_and_produce_HAND.sh
  src/heal_bridges_osm.py
  src/run_unit_wb.sh
Labels: bug

#1159 [5pt] PR: Update nws_lid dataset with Alaska sites
  docs/CHANGELOG.md
  tools/generate_nws_lid.py
Labels: enhancement, CatFIM, FIM4

#1156 [1pt] PR: Healed hand removing hydro-conditioning artifacts and testing
  config/params_template.env
  docs/CHANGELOG.md
  src/delineate_hydros_and_produce_HAND.sh
  tools/analyze_for_missing_FIM_cells.py
Labels: enhancement, FIM4

#1094 [1pt] PR: Update benchmark flows in AHPS domain
  data/update_benchmark_flows.py
  docs/CHANGELOG.md
  tools/tools_shared_variables.py
Labels: bug, testing

#1135 [1pt] PR: Add CRS handling to USGS gage processing
  docs/CHANGELOG.md
  src/run_by_branch.sh
  src/run_unit_wb.sh
  src/usgs_gage_crosswalk.py
  src/usgs_gage_unit_setup.py
Labels: bug

#1170 [1pt] PR: Hotfix for pyogrio arrow
  docs/CHANGELOG.md
  src/usgs_gage_crosswalk.py
  src/usgs_gage_unit_setup.py
  tools/rating_curve_comparison.py
Labels: bug, FIM4

#1166 [1pt] PR: Bridge inundation points
  config/deny_branch_zero.lst
  config/deny_branches.lst
  data/bridges/pull_osm_bridges.py
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/aggregate_by_huc.py
  src/delineate_hydros_and_produce_HAND.sh
  src/heal_bridges_osm.py
Labels: enhancement

#1172 [1pt] PR: Remove loading of apache-arrow repository
  Dockerfile
  Pipfile
  Pipfile.lock
  docs/CHANGELOG.md
Labels: bug
