Repository NOAA-OWP/inundation-mapping, pull requests merged in 2024-04, with the labels that each got.

#1110 [1pt] PR: Updates for newer openjdk and black packages
  .pre-commit-config.yaml
  Dockerfile
  Pipfile
  Pipfile.lock
  data/aws/aws_base.py
  docs/CHANGELOG.md
  src/src_roughness_optimization.py
  src/usgs_gage_crosswalk.py
  tools/overlapping_inundation.py
  tools/rating_curve_comparison.py
  unit_tests/__template.py
  unit_tests/aggregate_branch_lists_test.py
  unit_tests/clip_vectors_to_wbd_test.py
  unit_tests/derive_level_paths_test.py
  unit_tests/filter_catchments_and_add_attributes_test.py
  unit_tests/generate_branch_list_csv_test.py
  unit_tests/generate_branch_list_test.py
  unit_tests/inundate_gms_test.py
  unit_tests/inundation_test.py
  unit_tests/outputs_cleanup_test.py
  unit_tests/rating_curve_comparison_test.py
  unit_tests/shared_functions_test.py
  unit_tests/split_flows_test.py
  unit_tests/usgs_gage_crosswalk_test.py
Labels: enhancement, FIM4

#1114 [1pt] PR: Updates for pkgs pillow, idna and openpynx
  Pipfile
  Pipfile.lock
  README.md
  data/ble/ble_benchmark/Dockerfile
  data/ble/ble_benchmark/Pipfile
  data/ble/ble_benchmark/Pipfile.lock
  data/ble/ble_benchmark/README.md
  docs/CHANGELOG.md
Labels: Med Priority, dependencies, FIM4

#1106 [1pt] PR: Update FIM pipeline to process in Alaska
  data/wbd/generate_pre_clip_fim_huc8.py
  docs/CHANGELOG.md
  src/bash_variables.env
  src/check_huc_inputs.py
  src/derive_level_paths.py
  src/run_by_branch.sh
  src/run_unit_wb.sh
  src/utils/shared_variables.py
Labels: enhancement

#1103 [1pt] PR: Add checks for intermediate files in AGREE
  docs/CHANGELOG.md
  src/agreedem.py
Labels: Low Priority

#1081 [1pts] PR: synthetic rating curve calibration with USGS rating and up/down tracing
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/src_adjust_usgs_rating_trace.py
  src/src_roughness_optimization.py
  src/utils/shared_variables.py
Labels: enhancement
