Repository NOAA-OWP/inundation-mapping, pull requests merged in 2025-07, with the labels that each got.

#1574 [3pt] PR: Update ngvd_to_navd_ft conversion function to fix lat/lon bug and incorporate Alaska
  data/nws/preprocess_ahps_nws.py
  data/usgs/preprocess_ahps_usgs.py
  data/usgs/rating_curve_get_usgs_curves.py
  docs/CHANGELOG.md
  tools/catfim/generate_categorical_fim.py
  tools/tools_shared_functions.py
Labels: bug

#1539 [1pt] Update CatFIM site comparison tool to have the proper outputs for HydroVis release
  docs/CHANGELOG.md
  tools/catfim/catfim_sites_compare.py
Labels: CatFIM

#1573 [1pt] PR: Fix CatFIM inundate gms errors
  data/nws/preprocess_ahps_nws.py
  data/usgs/preprocess_ahps_usgs.py
  data/usgs/rating_curve_get_usgs_curves.py
  docs/CHANGELOG.md
  tools/catfim/ahps_restricted_sites.csv
  tools/catfim/generate_categorical_fim.py
  tools/catfim/generate_categorical_fim_flows.py
  tools/catfim/generate_categorical_fim_mapping.py
  tools/inundate_gms.py
  tools/tools_shared_functions.py
Labels: bug, CatFIM, Ready_to_Merge

#1543 [5pt] Incorporate roads into FIM
  data/roads/pull_osm_roads.py
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/aggregate_by_huc.py
  src/bash_variables.env
  src/delineate_hydros_and_produce_HAND.sh
  src/heal_bridges_osm.py
  src/process_roads_fimpact.py
  tools/road_inundation.py
Labels: enhancement

#1591 [1pt] PR: Remove buffer clipping from streams below HUC
  data/wbd/clip_vectors_to_wbd.py
  data/wbd/generate_pre_clip_fim_huc8.py
  docs/CHANGELOG.md
  src/agreedem.py
  src/bash_variables.env
  src/run_by_branch.sh
  src/stream_branches.py
Labels: bug, Inputs

#1595 [1pt] PR: Clip NWM streams at the land/sea mask
  docs/CHANGELOG.md
Labels: bug, Ready_to_Merge, Inputs

#1590 [1pt] PR: Ripple updates inc multiproc for Ripple FIM 100 data downloads
  data/ripple/get_s3_folder.sh
  data/ripple/get_s3_folders_from_list.sh
  data/ripple/hecras_boundaries.ipynb
  data/ripple/hecras_processing.ipynb
  data/ripple/ripple_shared_tools.sh
  docs/CHANGELOG.md
Labels: enhancement

#1584 [1pt] PR: Minor adj to test_case_by_hydroid
  docs/CHANGELOG.md
  tools/test_case_by_hydro_id.py
Labels: enhancement

#1580 [1pt] PR: Fix eval_plots for env file and misc cleanup
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CHANGELOG.md
  src/aggregate_fim_outputs.py
  src/finalize_srcs.py
  src/reset_mannings.py
  tools/adjust_rc_with_feedback.py
  tools/eval_plots.py
  tools/pixel_counter.py
Labels: enhancement
