Repository NOAA-OWP/inundation-mapping, pull requests merged in 2025-06, with the labels that each got.

#1552 [1pt] PR: dev-optz-mannings
  docs/CHANGELOG.md
  src/bash_variables.env
Labels: Rating Curves, FIM4

#1545 [1pt] PR: Update deny branches
  config/deny_branches.lst
  docs/CHANGELOG.md
Labels: FIM4, good first issue

#1511 [2pt] PR: Bathymetry Preprocessing and Adjustment Updates
  data/bathymetry/preprocess_bathymetry.py
  docs/CHANGELOG.md
  src/bash_variables.env
  src/bathymetric_adjustment.py
Labels: Rating Curves, Inputs

#1546 [2pt] PR: hydrotable updates inc parquet
  config/deny_branch_unittests.lst
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/add_crosswalk.py
  src/aggregate_by_huc.py
  src/src_manual_calibration.py
  src/update_htable_src.py
Labels: enhancement, High Priority

#1541 [1pt] PR: fixed AK lakes bugs
  docs/CHANGELOG.md
  src/bash_variables.env
  src/split_flows.py
Labels: bug

#1563 [3pt] Lofi fixes
  docs/CHANGELOG.md
  tools/lofi/probabilistic_inundation.py
Labels: enhancement

#1556 [1pt]: PR: Docker merge depbot and overpy packages
  Pipfile
  Pipfile.lock
  docs/CHANGELOG.md
  src/utils/shared_functions.py
Labels: dependencies
