Repository NOAA-OWP/inundation-mapping, pull requests merged in 2025-09, with the labels that each got.

#1649 [1pt] PR: Add selected huc list feature to pull osm roads
  data/roads/pull_osm_roads.py
  docs/CHANGELOG.md
Labels: enhancement

#1606 [2pt] PR: Changes to pass optional arg for using the precalb_discharge_cms for inundate scripts
  docs/CHANGELOG.md
  tools/inundate_gms.py
  tools/inundate_mosaic_wrapper.py
  tools/inundation.py
  tools/run_test_case.py
  tools/synthesize_test_cases.py
Labels: enhancement

#1643 [1pt] PR: Update eval_plots code to look for the env file only when in spatial mode
  docs/CHANGELOG.md
  tools/eval_plots.py
  tools/eval_plots_stackedbar.py
Labels: bug

#1608 [1pt] PR: Use `fiona` to read files
  docs/CHANGELOG.md
  src/mask_dem.py
  src/mitigate_branch_outlet_backpool.py
Labels: bug, FIM4

#1647 [1pt] PR: Add multiproc to get usgs rating curves script
  data/bridges/make_dem_dif_for_bridges.py
  data/nfhl/download_fema_nfhl.py
  data/nws/preprocess_ahps_nws.py
  data/roads/pull_osm_roads.py
  data/usgs/get_usgs_rating_curves.py
  data/usgs/preprocess_ahps_usgs.py
  data/usgs/rating_curve_get_usgs_curves.py
  docs/CHANGELOG.md
  pyproject.toml
  src/bash_variables.env
  src/src_adjust_usgs_rating_trace.py
  src/utils/shared_functions.py
  tools/fimr_to_benchmark.py
  tools/generate_nws_lid.py
  tools/rating_curve_comparison.py
  tools/tools_shared_functions.py
Labels: enhancement
