Repository NOAA-OWP/inundation-mapping, pull requests merged in 2025-05, with the labels that each got.

#1489 [1pt] Update CatFIM to function properly when lakes GPKG unavailable
  docs/CHANGELOG.md
  tools/catfim/generate_categorical_fim.py
  tools/catfim/generate_categorical_fim_mapping.py
  tools/tools_shared_functions.py
Labels: bug, CatFIM

#1488 [5pt] PR: Houston Manual Calibration
  docs/CHANGELOG.md
  src/bash_variables.env
Labels: Rating Curves, Inputs

#1485 [1pt] PR: Ripple Tools bug fix
  data/ripple/get_s3_folder.sh
  data/ripple/get_s3_folders_from_list.sh
  docs/CHANGELOG.md
Labels: bug

#1472 [1pt] Add areal differencing and geopackage creation to CatFIM site compare tool
  docs/CHANGELOG.md
  tools/catfim/catfim_sites_compare.py
Labels: enhancement, CatFIM

#1494 [1pt] PR: Download FEMA NFHL
  data/nfhl/download_fema_nfhl.py
  docs/CHANGELOG.md
Labels: enhancement

#1512 [1pt] Improve legibility of status message for stage-based CatFIM sites removed due to USGS acceptance criteria
  docs/CHANGELOG.md
  tools/catfim/generate_categorical_fim.py
Labels: CatFIM

#1510 [5pt] Optimize pre-clipping code
  data/wbd/clip_vectors_to_wbd.py
  data/wbd/generate_pre_clip_fim_huc8.py
  docs/CHANGELOG.md
  src/bash_variables.env
  src/stream_branches.py
Labels: bug, enhancement

#1502 [5pt] PR: Implement general-purpose multiprocessing runner with logging
  data/bridges/make_dem_dif_for_bridges.py
  docs/CHANGELOG.md
  src/utils/shared_functions.py
Labels: enhancement

#1515 [1pt] PR: Modified FEMA nfhl download tool
  data/nfhl/download_fema_nfhl.py
  docs/CHANGELOG.md
Labels: bug

#1499 [1pt] PR: Nonmonotonic SRCs adjustment
  config/params_template.env
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/bash_variables.env
  src/bathymetric_adjustment.py
  src/delineate_hydros_and_produce_HAND.sh
  src/nonmonotonic_src_adjustment.py
Labels: enhancement, Rating Curves, FIM4

#1495 [2pt] PR: Thalweg notches adjustment
  docs/CHANGELOG.md
Labels: enhancement, Rating Curves, FIM4

#1505 [2pts] PR: integrating & prioritizing channel slope values for SRC calculation
  docs/CHANGELOG.md
  src/add_crosswalk.py
  src/bash_variables.env
  src/delineate_hydros_and_produce_HAND.sh
  src/identify_src_bankfull.py
  src/update_htable_src.py
Labels: enhancement

#1496 [2pt] PR: Flow longitudinal consistency
  config/params_template.env
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/bathymetric_adjustment.py
  src/longitudinal_flow_adjustment.py
  src/nonmonotonic_src_adjustment.py
Labels: enhancement, Rating Curves, FIM4, Depth

#1481 [1pt] PR: Adjust elevations in branch floodplains to address catchment boundary issue
  .pre-commit-config.yaml
  config/deny_branches.lst
  config/params_template.env
  data/nwm/fix_nwm_streams.py
  docs/CHANGELOG.md
  src/adjust_floodplains.py
  src/bash_variables.env
  src/derive_level_paths.py
  src/run_by_branch.sh
  src/run_unit_wb.sh
  src/src_adjust_spatial_obs.py
  src/stream_branches.py
Labels: bug, FIM4

#1530 [1pt] PR: Add NFHL layer on read_file
  docs/CHANGELOG.md
  src/adjust_floodplains.py
  src/stream_branches.py
Labels: bug

#1526 [1pt] PR: Fix for external levelpath intersecting WBD
  docs/CHANGELOG.md
  src/stream_branches.py
Labels: bug, FIM4

#1529 [1pt] PR: Fix for SVD error
  docs/CHANGELOG.md
  src/bathymetric_adjustment.py
  src/longitudinal_flow_adjustment.py
  src/nonmonotonic_src_adjustment.py
Labels: bug, High Priority, FIM4

#1527 [1pt] PR: Fix error for missing files when updating htables
  docs/CHANGELOG.md
  src/aggregate_by_huc.py
  src/update_htable_src.py
Labels: bug

#1531 [1pt] Post proc logs missing some headers
  docs/CHANGELOG.md
  fim_post_processing.sh
Labels: enhancement

#1533 [1pt]PR: Hotfix to handle hydrofab slope variable names
  docs/CHANGELOG.md
  src/add_crosswalk.py
  src/identify_src_bankfull.py
  src/subdiv_chan_obank_src.py
Labels: bug

#1206 [21pt] PR: Likelihood of Flood Inundation
  CITATION.cff
  config/deny_branch_zero.lst
  config/deny_branches.lst
  docs/CHANGELOG.md
  pyproject.toml
  src/add_crosswalk.py
  src/aggregate_by_huc.py
  src/delineate_hydros_and_produce_HAND.sh
  src/mask_dem.py
  src/src_adjust_spatial_obs.py
  src/subdiv_chan_obank_src.py
  src/utils/shared_functions.py
  tools/composite_inundation.py
  tools/convert_to_int16.py
  tools/inundate_events.py
  tools/inundate_gms.py
  tools/inundate_mosaic_wrapper.py
  tools/inundation.py
  tools/inundation_wrapper_custom_flow.py
  tools/inundation_wrapper_nwm_flows.py
  tools/lofi/probabilistic_bayesian_update.py
  tools/lofi/probabilistic_distribution_parameters.py
  tools/lofi/probabilistic_generate_metric_response_surfaces.py
  tools/lofi/probabilistic_inundation.py
  tools/lofi/probabilistic_version.py
  tools/mosaic_inundation.py
  tools/overlapping_inundation.py
  tools/run_test_case.py
  tools/synthesize_test_cases.py
  tools/tools_shared_functions.py
Labels: enhancement
