Repository NOAA-OWP/inundation-mapping, pull requests merged in 2025-01, with the labels that each got.

#1360 [5pt] PR: Fixed osmid and added huc column
  data/bridges/pull_osm_bridges.py
  docs/CHANGELOG.md
  src/aggregate_by_huc.py
Labels: bug, enhancement, Ready_to_Merge

#1048 [5pt] PR: Post-processing tool for inundation: interpolate water surface
  docs/CHANGELOG.md
  tools/interpolate_water_surface.py
Labels: enhancement, Ready_to_Merge

#1382 [1pt] PR: Clean up Python files in FIM pipeline
  data/create_vrt_file.py
  docs/CHANGELOG.md
  src/accumulate_headwaters.py
  src/add_crosswalk.py
  src/adjust_thalweg_lateral.py
  src/delineate_hydros_and_produce_HAND.sh
  src/filter_catchments_and_add_attributes.py
  src/getRasterInfoNative.py
  src/heal_bridges_osm.py
  src/make_rem.py
  src/make_stages_and_catchlist.py
  src/mitigate_branch_outlet_backpool.py
  src/reachID_grid_to_vector_points.py
  src/run_by_branch.sh
  src/run_unit_wb.sh
  src/split_flows.py
  src/unique_pixel_and_allocation.py
  tools/evaluate_crosswalk.py
  tools/pixel_counter.py
Labels: bug, refactoring, High Priority, Ready_to_Merge

#1389 [1pt] PR: Upgrade Python packages
  Pipfile
  Pipfile.lock
  docs/CHANGELOG.md
Labels: bug, dependencies, Ready_to_Merge

#1387 [1pt] PR: Bug fixes for test_cases (missing benchmark types)
  docs/CHANGELOG.md
  tools/run_test_case.py
  tools/synthesize_test_cases.py
Labels: bug, Ready_to_Merge, good first issue

#1379 [1pt] Update CatFIM metadata API pulls and add duplicate site filtering, add CatFIM vis files
  config/symbology/qgis/catfim_library.qml
  docs/CHANGELOG.md
  tools/catfim/generate_categorical_fim_flows.py
  tools/catfim/notebooks/eval_catfim_metadata.ipynb
  tools/catfim/notebooks/vis_catfim_cross_section.ipynb
  tools/catfim/vis_categorical_fim.py
Labels: bug, CatFIM, Ready_to_Merge

#1399 [1pt] Update stage-based CatFIM to prevent overflooding if stage + elevation is provided in lieu of stage 
  docs/CHANGELOG.md
  tools/catfim/generate_categorical_fim.py
  tools/catfim/generate_categorical_fim_mapping.py
Labels: CatFIM, Ready_to_Merge

#1388 [5pt] PR: Bug fixes for Sierra test (vertical lines)
  docs/CHANGELOG.md
  tools/rating_curve_comparison.py
Labels: bug, enhancement, Rating Curves, Ready_to_Merge

#1340 [1pt] PR: Rating curves adjustments with ml-bathymetry data and optimized mannN
  config/params_template.env
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/bash_variables.env
  src/bathymetric_adjustment.py
  src/delineate_hydros_and_produce_HAND.sh
Labels: enhancement, Rating Curves, FIM4, Ready_to_Merge

#1268 [2pt] PR: New SRC calibration point data w/ max extent
  data/nws/ahps_bench_polys_to_calb_pts.py
  data/nws/merge_nws_usgs_point_parquet.py
  docs/CHANGELOG.md
  src/bash_variables.env
Labels: Rating Curves, Ready_to_Merge

#1178 [1pt] PR: Create inputs for selected HUC(s)
  README.md
  data/get_sample_data.py
  data/wbd/generate_pre_clip_fim_huc8.py
  docs/CHANGELOG.md
  src/bash_variables.env
Labels: enhancement, refactoring, High Priority, Ready_to_Merge

#1413 [1pt] Implement denylist for flow-based CatFIM
  docs/CHANGELOG.md
  tools/catfim/ahps_restricted_sites.csv
  tools/catfim/generate_categorical_fim.py
  tools/catfim/generate_categorical_fim_flows.py
  tools/catfim/stage_based_ahps_restricted_sites.csv
Labels: CatFIM, Ready_to_Merge

#1404 [1pt] PR: fixed bug in` aggregate_by_huc.py`
  docs/CHANGELOG.md
  src/aggregate_by_huc.py
Labels: bug, Med Priority, Ready_to_Merge

#1401 [1pt] PR: Modified HUC processing duration system
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/duration_system.py
  src/run_unit_wb.sh
Labels: enhancement, Ready_to_Merge
