Repository NOAA-OWP/inundation-mapping, pull requests merged in 2025-03, with the labels that each got.

#1427 [1pt] PR: Avoid importing both GDAL and rasterio in the same Python interpreter session
  Dockerfile.owp
  Pipfile
  Pipfile.lock
  data/bathymetry/preprocess_bathymetry.py
  docs/CHANGELOG.md
  src/utils/shared_functions.py
  tools/inundate_nation.py
Labels: bug, refactoring, dependencies

#1447 [1pt] PR: Podman update for owp server
  Dockerfile.dev
  Dockerfile.owp
  docs/CHANGELOG.md
Labels: DevOps

#1406 [5pt] PR: Incorporate Lidar-Informed elevations for bridges
  .gitignore
  data/bridges/conda_fim_bridges_enviro.yml
  data/bridges/make_dem_dif_for_bridges.py
  data/bridges/make_rasters_using_lidar.py
  data/bridges/pull_osm_bridges.py
  data/bridges/setup_conda_for_make_rasters.txt
  data/create_vrt_file.py
  data/usgs/acquire_and_preprocess_3dep_dems.py
  data/wbd/generate_pre_clip_fim_huc8.py
  docs/CHANGELOG.md
  pyproject.toml
  src/aggregate_by_huc.py
  src/bash_variables.env
  src/delineate_hydros_and_produce_HAND.sh
  src/heal_bridges_osm.py
  src/run_by_branch.sh
  src/run_unit_wb.sh
  tools/bridge_inundation.py
Labels: enhancement

#1463 [1pt] PR: Bug fix to handle HUCs without any lidar-informed bridges
  docs/CHANGELOG.md
  src/heal_bridges_osm.py
Labels: bug

#1450 [1pt] Improve handling of test sites and duplicate sites in CatFIM, update CatFIM vis
  docs/CHANGELOG.md
  tools/catfim/ahps_restricted_sites.csv
  tools/catfim/generate_categorical_fim.py
  tools/catfim/generate_categorical_fim_flows.py
  tools/catfim/vis_categorical_fim.py
Labels: CatFIM

#1442 [1pt] Update CatFIM site comparison tool to create multiple comparisons and more descriptive output CSVs
  docs/CHANGELOG.md
  tools/catfim/catfim_sites_compare.py
Labels: enhancement, CatFIM

#1429 [1pt] PR: Tools for downloading / managing Ripple data
  .gitignore
  .pre-commit-config.yaml
  data/ripple/get_s3_folder.sh
  data/ripple/get_s3_folders_from_list.sh
  data/ripple/hecras_boundaries.ipynb
  docs/CHANGELOG.md
  fim_post_processing.sh
  fim_pre_processing.sh
  pyproject.toml
Labels: enhancement

#1469 [1pt] PR: Fix DEM aquire for gdal arg changes plus Fix DEM misalignment
  config/deny_branch_zero.lst
  config/deny_branches.lst
  config/deny_unit.lst
  data/usgs/acquire_and_preprocess_3dep_dems.py
  docs/CHANGELOG.md
  fim_post_processing.sh
  src/bash_variables.env
  src/run_unit_wb.sh
Labels: enhancement

#1477 [1pt] PR: Debugging HUC processing duration system
  docs/CHANGELOG.md
  src/duration_system.py
Labels: bug
